### ISSUE TITLE
ImportError : Circular dependency

### ISSUE THREAD

**Issue by grimknight** [paulgb/gcmap#3]
Help me out? 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-feef46587674> in <module>()
----> 1 from gcmap import GCMapper, Gradient

~/anaconda3/lib/python3.6/site-packages/gcmap/__init__.py in <module>()
      1 
----> 2 from gcmap import GCMapper
      3 from gradient import Gradient
      4 

ImportError: cannot import name 'GCMapper'

**Comment by paulgb** [comment]
Sorry for the slow reply, I was traveling. I have fixed this issue; pip update gcmap to get it.

**Comment by sonyasonya345** [comment]
Please help: 

my code (below): 

for year_chunk in chunk_years(year_list, years_per_interval):
    with open(file_route, 'rb') as fin:
        coordinate_pair_data = pickle.load(fin)
    print(year_chunk, coordinate_pair_data[:3])

    col_names = coordinate_pair_data.columns
    gcmap_input = []
    for name in col_names:
        data = coordinate_pair_data[name].tolist()
        gcmap_input.append(data)

    gcm = GCMapper()
    lons1 = gcmap_input[0]
    lats1 = gcmap_input[1]
    lons2 = gcmap_input[2]
    lats2 = gcmap_input[3]

    gcm.set_data(lons1, lats1, lons2, lats2)

    print('draw map')
    image = gcm.draw()


-----
error: 

([2018, 2017, 2016, 2015, 2014],          lon1      lat1        lon2       lat2
0  103.819836  1.352083  -87.675267  42.056459
1  103.819836  1.352083 -113.071332  37.676444
2  103.819836  1.352083    5.767272  45.191420)
draw map
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-53-566fb1266b2c> in <module>()
     35 #     try:
     36     print('draw map')
---> 37     image = gcm.draw()
     38 
     39     # save the image to this file rout

/usr/local/lib/python2.7/site-packages/gcmap/gcmap.pyc in draw(self)
    143                 # plot one point after the break on each sides so that the
    144                 # paths go to the edge of the screen
--> 145                 x1, y1 = pts[cut_point+2, :]
    146                 x2, y2 = pts[cut_point+1, :]
    147 

IndexError: index 100 is out of bounds for axis 0 with size 100
