### ISSUE TITLE
Help out: IndexError: index 100 is out of bounds for axis 0 with size 100

### ISSUE THREAD

**Issue by sonyasonya345** [paulgb/gcmap#4]
Please kindly help!

IndexError                                Traceback (most recent call last)
<ipython-input-53-566fb1266b2c> in <module>()
     35 #     try:
     36     print('draw map')
---> 37     image = gcm.draw()
     38 
     39     # save the image to this file rout

/usr/local/lib/python2.7/site-packages/gcmap/gcmap.pyc in draw(self)
    143                 # plot one point after the break on each sides so that the
    144                 # paths go to the edge of the screen
--> 145                 x1, y1 = pts[cut_point+2, :]
    146                 x2, y2 = pts[cut_point+1, :]
    147 

IndexError: index 100 is out of bounds for axis 0 with size 100

-----

Below is my code: 

```
for year_chunk in chunk_years(year_list, years_per_interval):
    with open(file_route, 'rb') as fin:
        coordinate_pair_data = pickle.load(fin)

    col_names = coordinate_pair_data.columns
    gcmap_input = []
    for name in col_names:
        data = coordinate_pair_data[name].tolist()
        gcmap_input.append(data)

    gcm = GCMapper()
    # lons1, lats1 are departure coordinates
    # lons2, lats2 are arrival coordinates
    lons1 = gcmap_input[0]
    lats1 = gcmap_input[1]
    lons2 = gcmap_input[2]
    lats2 = gcmap_input[3]

    gcm.set_data(lons1, lats1, lons2, lats2)

    print('draw map')
    image = gcm.draw()
```

**Comment by paulgb** [comment]
I'm on vacation without a laptop until Sept 4, I'll take a look after I'm
back.

**Comment by sonyasonya345** [comment]
Thank you  so much!!!!~~~~

**Comment by sonyasonya345** [comment]
Will wait for your reply~~~

**Comment by sonyasonya345** [comment]
Hi Paul, 

Sorry to bother you. Some do have time, definitely need some help with the bug in my gcmap. Great thank!

**Comment by paulgb** [comment]
Can you share your data file with me so I can see if I can recreate the issue? If you don't want to attach it on github you can send it to my github username at gmail.com.

**Comment by sonyasonya345** [comment]
> Can you share your data file with me so I can see if I can recreate the issue? If you don't want to attach it on github you can send it to my github username at gmail.com.

Sure, thank you. Will send to your gmail.~~

**Comment by sonyasonya345** [comment]
Hi Paul, 

My husband figured out the bug for me. The length of my data is over 2700 pairs of coordinates. And the default gc_resolution is 100; and since I have over 2700 pairs of coordinates, so I need HIGHER number of straight line segments used to approximate each great-circle curve. 

However, thank you so much for both you and my husband!!!

**Comment by paulgb** [comment]
Thanks for the update @sonyasonya345, glad you could resolve it.
