### ISSUE TITLE
Making Flight Simulation Video

### ISSUE THREAD

**Issue by oaishi** [paulgb/gcmap#5]
Hello, thanks for this awesome opensource package. I wanted to know if it is possible to make a simulation video using GCmap. Something similar to this:  [https://youtu.be/TIZHn3ECHpM](https://youtu.be/TIZHn3ECHpM)

**Comment by paulgb** [comment]
Hi Faria,

Unfortunately it is not.

-- Paul

**Comment by oaishi** [comment]
Dear @paulgb,

It's completely alright. Thank you so much for your quick reply.
